from datetime import timedelta
import os
env = os.environ.get('env')

ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "SET_SECURE_PASSWORD_HERE"
SECRET_KEY = "FLASK_SECRET_KEY"
SQLALCHEMY_DATABASE_URI = "sqlite:///novelapp.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False
JWT_SECRET_KEY = "JWT_SECRET_KEY"
JWT_ACCESS_TOKEN_EXPIRES = timedelta(hours=2)
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
REGISTRATION_DISABLED = False
MAINTENANCE_MODE = False
MAILGUN_DOMAIN = "MG_DOMAIN"
MAILGUN_API_KEY = "MG_API_KEY"
MAILGUN_FROM_EMAIL = "MG_EMAIL"
if env == "development":
    STRIPE_SECRET_KEY = "DEV_STRIPE_SECRET_KEY"
    STRIPE_WEBHOOK_SECRET = "DEV_STRIPE_WEBHOOK_SECRET"
    STRIPE_PUBLISHABLE_KEY = "DEV_STRIPE_PUBLISHABLE_KEY"
else:
    STRIPE_SECRET_KEY="PROD_STRIPE_SECRET_KEY"
    STRIPE_WEBHOOK_SECRET="PROD_STRIPE_WEBHOOK_SECRET"
    STRIPE_PUBLISHABLE_KEY="PROD_STRIPE_PUBLISHABLE_KEY"
OPENAI_API_KEY = "OPEN_API_KEY"
S3_IMAGE_BUCKET = "BUCKET_NAME"
S3_ENDPOINT = "BUCKET_URL"
S3_REGION = "BUCKET_REGION"
S3_IMAGE_ACCESS_KEY_ID = "BUCKET_ACCESS_KEY_ID"
S3_IMAGE_SECRET_KEY = "BUCKET_SECRET_KEY"
